project_id = "bqhqaufdkfvdbsdhtxhm"

[functions.ai-chat]
verify_jwt = false

[functions.check-admin]
verify_jwt = false

[functions.check-secrets]
verify_jwt = false

[functions.update-ai-secret]
verify_jwt = false
